require 'bundler/setup'
require 'prawn'

$count  = 2
$blue = false

def build(number)
  height = 378
  width = 874
  img = "logo.jpg"
  options = {page_size: [width, height],
             margin:    0}
  padded_number = sprintf("%03d", number)
  Prawn::Document.generate("ticket#{padded_number}.pdf", options) do
    if $blue
      img = "logo-blue.jpg"
      fill_color "89A5CE"
      rectangle [0, height], width, height
      fill
      fill_color "000000"
    end

    half_width = width / 2
    dash(1, space: 1)
    line [half_width, 10], [half_width, height - 10]
    stroke

    font "VeraMono.ttf"
    box_width = 100
    size = 32
    [0,box_width].each do |offset|
      text_box number.to_s, at: [half_width - offset, size + 50],
                            width: box_width,
                            align: :center,
                            size: size
    end

    img_size = 260
    img_x = (half_width - img_size) / 2
    img_y = height - ((height - img_size) / 2)
    image img, at: [img_x, img_y], width: img_size, height: img_size
    image img, at: [img_x + half_width, img_y], width: img_size, height: img_size
  end
end

task :tickets do
  [1,200].each { |n| build(n) }
end

task :clean do
  sh "rm ticket*"
end

task :default => :tickets
